trigger:
- master

jobs:
  - job: build
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

      - script: |
          npm install
          npm run build
        displayName: 'npm install and build'


      - task: CopyFiles@2
        inputs:
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)
          artifactName: MyBuildOutputs

  - job: test
    dependsOn: build
    steps:
      - script: 
          echo 'All test cases passes'
        displayName: 'Unit test'
  
  - deployment: deploy
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo Deployed to Dev