trigger:
- master

jobs:
  - job: build
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

      - script: |
          npm install
          npm run build
        displayName: 'npm install and build'


      - task: CopyFiles@2
        inputs:
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)
          artifactName: MyBuildOutputs

  - job: deploy
    steps:
      - script: 
          echo hello
        displayName: 'Deploy to Dev'