trigger:
- master

stages:
  - stage: deploy
    condition: eq(variables.shouldRun, 'deploy')
    displayName: 'Deploy'
    jobs:
      - job: 
        steps:
          - script: echo $(pipelineid1) 
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: 'dfc7d9bc-d749-475a-ae1b-113601aff5ce'
              definition: '22'
              buildVersionToDownload: 'specific'
              pipelineId: $(pipelineid1)
              artifactName: 'MyBuildOutputs'
              targetPath: '$(Pipeline.Workspace)'
      
          - script: cd $(Pipeline.Workspace) && ls
          - script: ls -ltr
          - script: ls 
      - deployment: deployToDev
        displayName: 'Deploy Dev'
        environment: Dev
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo Deployed to Dev
                - script: ls 