

trigger:
- master

stages:
  - stage: build
    condition: eq(variables.shouldRun, 'build')
    displayName: 'Build'
    jobs:
    - job: build
      
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
          displayName: 'Install Node.js'

        - script: |
            npm install
            npm run build
          displayName: 'npm install and build'


        - task: CopyFiles@2
          inputs:
            targetFolder: $(Build.ArtifactStagingDirectory)
        - task: PublishBuildArtifacts@1
          inputs:
            pathToPublish: $(Build.ArtifactStagingDirectory)
            artifactName: MyBuildOutputs
    
  - stage: test
    condition: eq(variables.shouldRun, 'test')
    displayName: 'Test'
    jobs:
      - job: test
        steps:
          - script: 
              echo 'All test cases passes'
            displayName: 'Unit test'
      

    

  - stage: deploy

  
    
    condition: eq(variables.shouldRun, 'deploy')
    displayName: 'Deploy'
    jobs:
      - job: 
        steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: specific
              project: 'deepaannjohn/pipelines-javascript'
              pipeline: '20'
              buildVersionToDownload: latest
              downloadType: 'single'
              artifactName: 'MyBuildOutputs'
              downloadPath: '$(System.ArtifactsDirectory)'

        
      - deployment: deployToDev
        displayName: 'Deploy Dev'
        
        environment: Dev
        strategy:
          runOnce:
            deploy:


              
              steps:
                - download: previous
                  artifact: MyBuildOutputs

                - script: echo Deployed to Dev

