

trigger:
- master

stages:
  - stage: build
    condition: eq(variables.shouldRun, 'build')
    displayName: 'Build'
    jobs:
    - job: build
      
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
          displayName: 'Install Node.js'

        - script: |
            npm install
            npm run build
          displayName: 'npm install and build'


        - task: CopyFiles@2
          inputs:
            targetFolder: $(Build.ArtifactStagingDirectory)
        - task: PublishBuildArtifacts@1
          inputs:
            pathToPublish: $(Build.ArtifactStagingDirectory)
            artifactName: MyBuildOutputs
    
  - stage: test
    condition: eq(variables.shouldRun, 'test')
    displayName: 'Test'
    jobs:
      - job: test
        steps:
          - script: 
              echo 'All test cases passes'
            displayName: 'Unit test'
      

    

  - stage: deploy

  
    
    condition: eq(variables.shouldRun, 'deploy')
    displayName: 'Deploy'
    jobs:
      - job: 
        steps:
      
          - task: DownloadPipelineArtifact@2
            inputs:
              source: specific
              
              
              
              runVersion: specific
              runBranch: 'refs/heads/master' 
              runId: 385
              path: '$(Pipeline.Workspace)'
              project: 'dfc7d9bc-d749-475a-ae1b-113601aff5ce'
              pipeline: '20'

                  
      - deployment: deployToDev
        displayName: 'Deploy Dev'
        
        environment: Dev
        strategy:
          runOnce:
            deploy:


              
              steps:
                

                - script: echo Deployed to Dev
                - script: ls 

