trigger: none



stages:
  - stage: deploy
    displayName: 'Deploy'
    jobs:
      - deployment: deployToprod
        displayName: 'Deploy Prod'
        environment: Prod
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo Deployed to Prod