trigger: none

resources:
  pipelines:
    - pipeline: mySourcePipeline
      source: deepaannjohn.pipelines-javascript
      trigger:
        branches:
        - master

stages:
  - stage: deploy
    displayName: 'Deploy'
    jobs:
      - deployment: deployToprod
        displayName: 'Deploy Prod'
        environment: Prod
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo Deployed to Prod